# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('ali', models.FloatField(verbose_name='\u963f\u91cc\u4e91\u8d39\u7528/\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='AwsCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('serviceCost', models.FloatField(verbose_name='\u8d39\u7528/\u5143')),
                ('supportCost', models.FloatField(verbose_name='\u8d39\u7528/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='AwsShareCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('service', models.FloatField(verbose_name='\u670d\u52a1\u8d39\u7528/\u7f8e\u5143')),
                ('support', models.FloatField(verbose_name='\u652f\u6301\u8d39\u7528/\u7f8e\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u7f8e\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u7f8e\u5143')),
                ('bigData', models.FloatField(verbose_name='\u5927\u6570\u636e\u5206\u644a/\u7f8e\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u7f8e\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='BigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('percentage', models.FloatField(verbose_name='\u6bd4\u4f8b')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='Cdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=100, verbose_name='\u57df\u540d')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('flux', models.CharField(max_length=30, verbose_name='\u6d41\u91cf')),
                ('startTime', models.CharField(max_length=50, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.CharField(max_length=50, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='CdnPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('percentage', models.FloatField(verbose_name='\u6bd4\u4f8b')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='ChinaPerMonthCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('qcloud', models.FloatField(verbose_name='qcloud\u8d39\u7528/\u5143')),
                ('ali', models.FloatField(verbose_name='\u963f\u91cc\u4e91\u8d39\u7528/\u5143')),
                ('zhaowei', models.FloatField(verbose_name='\u5146\u7ef4/\u5143')),
                ('lugu', models.FloatField(verbose_name='\u9c81\u8c37/\u5143')),
                ('ucloud', models.FloatField(verbose_name='ucloud\u8d39\u7528/\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u5143')),
                ('bigData', models.FloatField(verbose_name='\u5927\u6570\u636e\u5206\u644a/\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30, verbose_name='\u67e5\u8be2\u6708\u4efd')),
                ('prePayAmount', models.FloatField(verbose_name='\u5f53\u6708\u9884\u4ed8\u8d39/\u5206')),
                ('postPayAmount', models.FloatField(verbose_name='\u5f53\u6708\u540e\u4ed8\u8d39/\u5206')),
                ('returnAmount', models.FloatField(verbose_name='\u5f53\u6708\u9000\u6b3e/\u5206')),
                ('nextPostAmount', models.FloatField(verbose_name='\u4e0b\u6708\u540e\u4ed8\u8d39/\u5206')),
                ('totalExpense', models.FloatField(verbose_name='\u5408\u8ba1/\u5206')),
            ],
        ),
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('broadbandUsage', models.FloatField(verbose_name='\u5e26\u5bbd\u4f7f\u7528\u91cf')),
                ('percentage', models.FloatField(verbose_name='\u6bd4\u4f8b')),
                ('region', models.CharField(max_length=10, verbose_name='\u5730\u57df')),
                ('expense', models.FloatField(verbose_name='\u8d39\u7528/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='LuGuCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('lugu', models.FloatField(verbose_name='\u9c81\u8c37/\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=30, verbose_name='\u7528\u9014')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('cost', models.FloatField(verbose_name='\u8d39\u7528/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPlatCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat', models.CharField(max_length=30, verbose_name='\u5e73\u53f0')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('cost', models.FloatField(verbose_name='\u8d39\u7528/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='OverseasPerMonthCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('service', models.FloatField(verbose_name='\u670d\u52a1\u8d39\u7528/\u7f8e\u5143')),
                ('support', models.FloatField(verbose_name='\u652f\u6301\u8d39\u7528/\u7f8e\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u7f8e\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u7f8e\u5143')),
                ('bigData', models.FloatField(verbose_name='\u5927\u6570\u636e\u5206\u644a/\u7f8e\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u7f8e\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('percentage', models.FloatField(verbose_name='\u6bd4\u4f8b')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u9879\u76eeID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='QcloudCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('qcloud', models.FloatField(verbose_name='qcloud\u8d39\u7528/\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='QcloudDeal',
            fields=[
                ('dealId', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355ID')),
                ('payMode', models.CharField(max_length=20, verbose_name='\u652f\u4ed8\u6a21\u5f0f')),
                ('payType', models.CharField(max_length=20, verbose_name='\u652f\u4ed8\u7c7b\u578b')),
                ('platform', models.CharField(max_length=20, verbose_name='\u5e73\u53f0')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('productCode', models.CharField(max_length=50, verbose_name='\u4ea7\u54c1\u7f16\u7801')),
                ('subProductCode', models.CharField(max_length=50, verbose_name='\u5b50\u4ea7\u54c1\u7f16\u7801')),
                ('instanceId', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8bID')),
                ('amount', models.FloatField(verbose_name='\u6263\u8d39\u91d1\u989d/\u5206')),
                ('startTime', models.CharField(max_length=30, verbose_name='\u8ba1\u8d39\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.CharField(max_length=30, verbose_name='\u8ba1\u8d39\u7ed3\u675f\u65f6\u95f4')),
                ('projectId', models.CharField(max_length=10, verbose_name='\u9879\u76eeID')),
                ('month', models.CharField(max_length=30, verbose_name='\u67e5\u8be2\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='UcloudCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('ucloud', models.FloatField(verbose_name='ucloud\u8d39\u7528/\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
        migrations.CreateModel(
            name='ZhaoWeiCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
                ('version', models.CharField(max_length=10, verbose_name='\u7248\u672c')),
                ('zhaowei', models.FloatField(verbose_name='\u5146\u7ef4/\u5143')),
                ('common', models.FloatField(verbose_name='\u516c\u53f8\u516c\u5171\u5206\u644a/\u5143')),
                ('plat', models.FloatField(verbose_name='\u5e73\u53f0\u5206\u644a/\u5143')),
                ('bigData', models.FloatField(verbose_name='\u5927\u6570\u636e\u5206\u644a/\u5143')),
                ('total', models.FloatField(verbose_name='\u9879\u76ee\u8d39\u7528\u5408\u8ba1/\u5143')),
                ('month', models.CharField(max_length=10, verbose_name='\u6708\u4efd')),
            ],
        ),
    ]
